GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/posts/1/likes

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "bswoo04@gm.com",
    "password": "123456d--"
  }